/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("./models/Context-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<mesh geometry={nodes.natural_land.geometry} material={materials.land} />
			<mesh geometry={nodes.Water.geometry} material={materials.water_big} />
			<mesh
				geometry={nodes.Building_5.geometry}
				material={materials.buildings}
			/>
			<mesh
				geometry={nodes.Pavements.geometry}
				material={materials.sidewalks_material}
			/>
			<mesh geometry={nodes.Park.geometry} material={materials.park} />
			<mesh
				geometry={nodes.Buildng_1.geometry}
				material={materials.buildings}
			/>
			<mesh
				geometry={nodes.Buildng_2_1.geometry}
				material={materials.buildings}
			/>
			<mesh
				geometry={nodes.Buildng_2_2.geometry}
				material={materials.buildings}
			/>
			<mesh
				geometry={nodes.Buildng_3_1.geometry}
				material={materials.buildings}
			/>
			<mesh
				geometry={nodes.Buildng_3_2.geometry}
				material={materials.buildings}
			/>
			<mesh
				geometry={nodes.Buildng_4_1.geometry}
				material={materials.buildings}
			/>
			<mesh
				geometry={nodes.Buildng_4_2.geometry}
				material={materials.buildings}
			/>
		</group>
	);
}

useGLTF.preload("./models/Context-transformed.glb");
